/**
 * `scopegate policies review|accept|reject` (EPIC-08 H8.6) — the PR-style
 * review flow for agent-proposed rules in `policies.pending.yaml`.
 *
 * Write asymmetry (README / SKILL rule 4): agents PROPOSE, humans decide.
 * `policies accept` is the ONLY automated path that writes `policies.yaml`,
 * and it is guarded exactly like approvals (interactive TTY or
 * SCOPEGATE_APPROVAL_TOKEN) so the agent cannot merge its own proposals.
 *
 * Accept mechanics:
 *   - The rule is appended to the agent's `capabilities` in policies.yaml as
 *     `{match, ttl?, auto_approve: true}` — accepting a proposal means
 *     auto-approving what it matches. Anything stronger (require, redact,
 *     limits) stays a manual edit, as proposeRule's field allowlist intends.
 *   - policies.yaml is edited through the YAML AST (parseDocument) so
 *     existing human comments survive, validated with the engine's own
 *     validatePoliciesFile (no parsing logic duplicated here), and written
 *     atomically (tmp + rename, 0600). On ANY validation failure nothing is
 *     written — fail-closed, last-good file untouched.
 *   - The proposal is marked `accepted`/`rejected` in the pending file
 *     (append-style history is kept; rejected proposals stay as an audit
 *     trail) and the decision is audited as policy_accepted/policy_rejected.
 */
import fs from "node:fs";
import YAML, { isMap, isSeq, type YAMLSeq } from "yaml";
import {
  PENDING_POLICIES_PATH,
  POLICIES_PATH,
  configExists,
  ensureDir,
  loadConfig,
} from "../config/config.js";
import { validatePoliciesFile } from "../policy/engine.js";
import { audit } from "../audit/log.js";
import { assertHumanOrigin, type ApprovalOrigin } from "./approvals-cli.js";

export interface ProposalEntry {
  /** 1-based position in the pending file — the stable id accept/reject take. */
  index: number;
  proposedAt?: string;
  agentId?: string;
  rule?: { match?: string; ttl?: string };
  justification?: string;
  status?: string;
  lint?: string;
  resolvedAt?: string;
  resolutionReason?: string;
}

/* ------------------------------------------------------------------------ */
/* Pending file (multi-doc YAML, machine-generated by proposeRule)           */
/* ------------------------------------------------------------------------ */

interface PendingDoc {
  value: ProposalEntry;
}

function readPendingDocs(): PendingDoc[] {
  if (!fs.existsSync(PENDING_POLICIES_PATH)) return [];
  const raw = fs.readFileSync(PENDING_POLICIES_PATH, "utf8");
  if (!raw.trim()) return [];
  const docs = YAML.parseAllDocuments(raw);
  const out: PendingDoc[] = [];
  for (const d of docs) {
    if (d.errors.length > 0) {
      throw new Error(
        `${PENDING_POLICIES_PATH} is corrupt (${d.errors[0].message}) — refusing to rewrite it. Fix it manually.`,
      );
    }
    const v = d.toJS() as unknown;
    if (v && typeof v === "object") out.push({ value: v as ProposalEntry });
  }
  return out;
}

export function readProposals(): ProposalEntry[] {
  return readPendingDocs().map((d, i) => ({ ...d.value, index: i + 1 }));
}

/** Rewrite the whole pending file in proposeRule's own format, atomically. */
function writePendingDocs(docs: PendingDoc[]): void {
  ensureDir();
  const out = docs.map((d) => "---\n" + YAML.stringify(d.value)).join("");
  const tmp = `${PENDING_POLICIES_PATH}.tmp`;
  fs.writeFileSync(tmp, out, { mode: 0o600 });
  fs.renameSync(tmp, PENDING_POLICIES_PATH);
}

/* ------------------------------------------------------------------------ */
/* policies.yaml append (AST edit: preserves human comments)                 */
/* ------------------------------------------------------------------------ */

/** Atomic write: sibling tmp file + rename, mode 0600 (config.ts pattern). */
function atomicWrite(filePath: string, data: string): void {
  const tmp = `${filePath}.tmp`;
  fs.writeFileSync(tmp, data, { mode: 0o600 });
  fs.renameSync(tmp, filePath);
}

function appendRuleToPolicies(opts: {
  agentId: string;
  rule: { match: string; ttl?: string };
  proposalIndex: number;
}): void {
  const raw = fs.existsSync(POLICIES_PATH)
    ? fs.readFileSync(POLICIES_PATH, "utf8")
    : "version: 1\nagents: {}\n";
  const doc = YAML.parseDocument(raw);
  if (doc.errors.length > 0) {
    throw new Error(
      `${POLICIES_PATH} is not valid YAML (${doc.errors[0].message}) — fix it manually; nothing was written.`,
    );
  }
  if (doc.contents === null) {
    doc.set("version", 1);
    doc.set("agents", doc.createNode({}));
  }

  let agentsNode = doc.get("agents", true);
  if (agentsNode === undefined || agentsNode === null) {
    doc.set("agents", doc.createNode({}));
    agentsNode = doc.get("agents", true);
  }
  if (!isMap(agentsNode)) {
    throw new Error(`${POLICIES_PATH}: 'agents' is not a map — fix it manually; nothing was written.`);
  }

  let agentNode = agentsNode.get(opts.agentId, true);
  if (agentNode === undefined || agentNode === null) {
    agentsNode.set(doc.createNode(opts.agentId), doc.createNode({ capabilities: [] }));
    agentNode = agentsNode.get(opts.agentId, true);
  }
  if (!isMap(agentNode)) {
    throw new Error(
      `${POLICIES_PATH}: agents.${opts.agentId} is not a map — fix it manually; nothing was written.`,
    );
  }

  let capsNode = agentNode.get("capabilities", true);
  if (capsNode === undefined || capsNode === null) {
    agentNode.set("capabilities", doc.createNode([]));
    capsNode = agentNode.get("capabilities", true);
  }
  if (!isSeq(capsNode)) {
    throw new Error(
      `${POLICIES_PATH}: agents.${opts.agentId}.capabilities is not a list — fix it manually; nothing was written.`,
    );
  }

  const rule: Record<string, unknown> = { match: opts.rule.match };
  if (opts.rule.ttl !== undefined) rule.ttl = opts.rule.ttl;
  rule.auto_approve = true;
  const ruleNode = doc.createNode(rule);
  ruleNode.comment = ` accepted from agent proposal #${opts.proposalIndex} (scopegate policies accept)`;
  (capsNode as YAMLSeq).add(ruleNode);

  // Reuse the engine's own schema validation on the FINAL document — no
  // parsing duplicated, and a broken result is never written (fail-closed).
  try {
    validatePoliciesFile(doc.toJS({ maxAliasCount: -1 }));
  } catch (e) {
    throw new Error(
      `accepting proposal #${opts.proposalIndex} would make ${POLICIES_PATH} invalid: ` +
        `${(e as Error).message}. Nothing was written.`,
    );
  }

  ensureDir();
  atomicWrite(POLICIES_PATH, String(doc));
}

/* ------------------------------------------------------------------------ */
/* Audit                                                                     */
/* ------------------------------------------------------------------------ */

function auditAgentId(): string {
  try {
    if (configExists()) return loadConfig().agentId;
  } catch {
    /* fall through to the env/default identity */
  }
  return process.env.SCOPEGATE_AGENT_ID ?? "scopegate-cli";
}

function bestEffortAudit(kind: "policy_accepted" | "policy_rejected", detail: Record<string, unknown>): void {
  try {
    audit(auditAgentId(), kind, detail);
  } catch (e) {
    console.error(`[scopegate] warn: audit(${kind}) failed: ${(e as Error).message}`);
  }
}

/* ------------------------------------------------------------------------ */
/* Accept / reject                                                           */
/* ------------------------------------------------------------------------ */

function getPendingProposal(index: number): { docs: PendingDoc[]; doc: PendingDoc } {
  if (!Number.isInteger(index) || index < 1) {
    throw new Error(`Invalid proposal number '${index}' — a positive integer is expected.`);
  }
  const docs = readPendingDocs();
  const doc = docs[index - 1];
  if (!doc) {
    const pending = docs.filter((d) => d.value.status === "pending_human_review").length;
    throw new Error(
      `No proposal #${index} in ${PENDING_POLICIES_PATH} (${docs.length} on file, ${pending} pending). ` +
        `Run \`scopegate policies review\` to see them.`,
    );
  }
  if (doc.value.status !== "pending_human_review") {
    throw new Error(
      `Proposal #${index} is already '${doc.value.status ?? "unknown"}' — only ` +
        `'pending_human_review' proposals can be decided.`,
    );
  }
  return { docs, doc };
}

export function acceptProposal(
  index: number,
  origin: ApprovalOrigin,
): { agentId: string; match: string; ttl?: string } {
  const { docs, doc } = getPendingProposal(index);
  const p = doc.value;
  const agentId = p.agentId;
  const match = p.rule?.match;
  if (!agentId || !match) {
    throw new Error(
      `Proposal #${index} is malformed (missing agentId or rule.match) — reject it instead.`,
    );
  }
  appendRuleToPolicies({
    agentId,
    rule: { match, ...(p.rule?.ttl !== undefined ? { ttl: p.rule.ttl } : {}) },
    proposalIndex: index,
  });
  p.status = "accepted";
  p.resolvedAt = new Date().toISOString();
  writePendingDocs(docs);
  bestEffortAudit("policy_accepted", {
    index,
    proposedBy: agentId,
    match,
    ttl: p.rule?.ttl ?? null,
    decidedBy: `human:cli:${origin}`,
  });
  return { agentId, match, ...(p.rule?.ttl !== undefined ? { ttl: p.rule.ttl } : {}) };
}

export function rejectProposal(index: number, reason: string, origin: ApprovalOrigin): void {
  const trimmed = (reason ?? "").trim();
  if (!trimmed) {
    throw new Error(`--reason is required for reject — it stays in the pending file as history.`);
  }
  const { docs, doc } = getPendingProposal(index);
  const p = doc.value;
  p.status = "rejected";
  p.resolvedAt = new Date().toISOString();
  p.resolutionReason = trimmed;
  writePendingDocs(docs);
  bestEffortAudit("policy_rejected", {
    index,
    proposedBy: p.agentId ?? null,
    match: p.rule?.match ?? null,
    reason: trimmed,
    decidedBy: `human:cli:${origin}`,
  });
}

/* ------------------------------------------------------------------------ */
/* CLI entry points (guard + print)                                          */
/* ------------------------------------------------------------------------ */

export function runPoliciesReview(opts: { all?: boolean }): void {
  const proposals = readProposals();
  const shown = opts.all
    ? proposals
    : proposals.filter((p) => p.status === "pending_human_review");
  if (shown.length === 0) {
    console.log(
      opts.all
        ? `(no proposals in ${PENDING_POLICIES_PATH})`
        : "(no proposals pending human review)",
    );
    return;
  }
  console.log(
    opts.all
      ? `POLICY PROPOSALS (${shown.length})`
      : `POLICY PROPOSALS PENDING REVIEW (${shown.length})`,
  );
  for (const p of shown) {
    const state = p.status ?? "unknown";
    console.log(`  #${p.index}  [${state}]`);
    console.log(`    agent:     ${p.agentId ?? "?"}`);
    console.log(`    match:     ${p.rule?.match ?? "?"}`);
    console.log(`    ttl:       ${p.rule?.ttl ?? "(none)"}`);
    if (p.justification) console.log(`    why:       ${p.justification}`);
    if (p.lint) console.log(`    LINT:      ${p.lint} — collides with hard limits; accepting will NOT make it effective`);
    if (p.proposedAt) console.log(`    proposed:  ${p.proposedAt}`);
    if (p.status === "pending_human_review") {
      console.log(`    decide:    scopegate policies accept ${p.index}  |  scopegate policies reject ${p.index} --reason "..."`);
    } else {
      console.log(`    resolved:  ${p.resolvedAt ?? "?"}${p.resolutionReason ? ` — ${p.resolutionReason}` : ""}`);
    }
  }
}

export function runPoliciesAccept(n: string): void {
  const origin = assertHumanOrigin();
  const res = acceptProposal(Number(n), origin);
  console.log(
    `[scopegate] proposal #${n} ACCEPTED (origin: ${origin}) — appended to agents.${res.agentId}.capabilities ` +
      `in policies.yaml as { match: "${res.match}"${res.ttl ? `, ttl: "${res.ttl}"` : ""}, auto_approve: true }.`,
  );
  console.log(`[scopegate] running gateways pick it up via hot-reload (<1s).`);
}

export function runPoliciesReject(n: string, opts: { reason?: string }): void {
  const origin = assertHumanOrigin();
  rejectProposal(Number(n), opts.reason ?? "", origin);
  console.log(
    `[scopegate] proposal #${n} REJECTED (origin: ${origin}) — kept in policies.pending.yaml as history. ` +
      `policies.yaml was NOT touched.`,
  );
}
